--- 
- hosts: all
  become: yes
  tasks:
    - name: Criação de Grupos de Usuarios
      group:  
        name: "{{ item }}"
        state: present
      with_items:
           - g_ti
           - g_diretoria                       
           - g_suporte 
    - name: Adicionando Usuario Suporte
      user:
        name: suporte
        comment: Suporte TI
        uid: 2000
        shell: /bin/bash
        group: g_ti
        groups: g_diretoria,g_suporte  
        password: '1234'
        update_password: on_create
        append: yes  
                                     
